postgres:
  host:
  port: 5432
  database: hive_metastore
  
  #TODO: Should be able to provide username and password from a secret instead of raw values
  username:
    rawValue: postgres
  password:
    rawValue: postgres

autoCreateSchema: false
warehouseDir: file:///tmp

blobStorages:
  # TODO: Support other Azure authentication methods then SharedKey
  azureStorageAccounts: []
    # - name:
    #   key:

  gcsConfiguration:
    projectId:
    base64KeyFile:
  
  s3aConfiguration:
    accessKeyId:
    secretAccessKey:
    endpoint:
    pathStyleAccess: false


hiveConfigParameters:
  - key: hive.metastore.uris
    value: trift://0.0.0.0:9083
  - key: hive.metastore.schema.verification
    value: false
  - key: hive.metastore.schema.verification.record.version
    value: false
  - key: hive.metastore.event.db.notification.api.auth
    value: false
  - key: hadoop.proxyuser.hive.hosts
    value: HS2_HOST
  - key: hadoop.proxyuser.hive.groups
    value: "*"
  - key: datanucleus.autoStartMechanism
    value: SchemaTable
  - key: metastore.expression.proxy
    value: org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy
  - key: metastore.task.threads.always
    value: org.apache.hadoop.hive.metastore.events.EventCleanerTask,org.apache.hadoop.hive.metastore.MaterializationsCacheCleanerTask

image:
  repository: andreclaudino/hive-metastore
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  andreclaudino/service: hive-metastore

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9083

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
